@Api_HostAddress = http://localhost:5157

GET {{Api_HostAddress}}/product/listAllProducts?category=jewelery&&stock=0
Accept: application/json

###

POST {{Api_HostAddress}}/product/
Accept: application/json

###
DELETE {{Api_HostAddress}}/product/
Accept: application/json
